/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED
#define CONFIG_X86_PLATFORM 1
#undef  CONFIG_IMX_PLATFORM
#define REGION_US 1
#undef  REGION_EU
#undef  REGION_JAPAN
#undef  REGION_OTHERS
#undef  AMPDU_AGGR_SUPPORT
#undef  ONEBOX_DEBUG_ENABLE
#undef  CHIP_ENABLED
#undef  AUTO_RATE_SUPPORT
#undef  EEPROM_READ_EN
#undef  RSI_SDIO_MULTI_BLOCK_SUPPORT
#undef  SECURITY_SUPPORT
#undef  ENABLE_P2P_SUPPORT
#undef  IEEE80211_AMPDU_AGE
