/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED
#define ENABLE_USB 1
#define ENABLE_SDIO 1
#define RSI_CONFIG_LINUX 1
#undef  RSI_CONFIG_ANDROID
#undef  ONEBOX_CONFIG_NL80211
#undef  HOSTAPD_SUPPORT
#define ENABLE_WLAN 1
#define ENABLE_BT 1
#define ENABLE_ZIGB 1
